// <auto-generated />
using MVCDinos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MVCDinos.Migrations
{
    [DbContext(typeof(DinosaurContext))]
    partial class DinosaurContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MVCDinos.Models.Class", b =>
                {
                    b.Property<string>("ClassID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClassDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClassEasyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClassName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClassID");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("MVCDinos.Models.Dinosaur", b =>
                {
                    b.Property<int>("DinosaurID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BriefDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClassID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DinosaurName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LengthFt")
                        .HasColumnType("int");

                    b.Property<int>("LivedYearsAgo")
                        .HasColumnType("int");

                    b.Property<string>("NameMeans")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PeriodID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pronounced")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WeightLbs")
                        .HasColumnType("int");

                    b.HasKey("DinosaurID");

                    b.ToTable("Dinosaurs");
                });

            modelBuilder.Entity("MVCDinos.Models.Period", b =>
                {
                    b.Property<string>("PeriodID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PeriodName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PeriodID");

                    b.ToTable("Periods");
                });
#pragma warning restore 612, 618
        }
    }
}
